 _format_version: "3.0"
 _transform: true

 services:
 - host: chatbot-chats
   name: chatbot-chats
   port: 3000
   protocol: http
   routes:
   - name: chats
     paths:
     - /chats
     strip_path: false

 - host: chatbot-messages
   name: chatbot-messages
   port: 3000
   protocol: http
   routes:
   - name: messages
     paths:
     - /messages
     strip_path: false




