 _format_version: "3.0"
 _transform: true

 services:
 - host: chatbot-chats
   name: chatbot-chats
   port: 3000
   protocol: http
   routes:
   - name: chats
     paths:
     - /chats
     strip_path: false

# _format_version: "1.1"

# services:
#   - name: chatbot-chats-service
#     url: http://chatbot-chats:3003
#     routes:
#       - name: chatbot-chats-route
#         paths:
#           - /


