services:
  chatbot-user:
    build:
      context: ./chatbot-user
    ports:
      - "3001:3000"
    volumes:
      - ./chatbot-user:/app
      - ./shared-lib:/app/node_modules/@chatbot/shared-lib
    command: npm run start:dev
    depends_on:
      - db
      - rabbitmq

  chatbot-logs:
    build:
      context: ./chatbot-logs
    ports:
      - "3002:3000"
    volumes:
      - ./chatbot-logs:/app
      - ./shared-lib:/app/node_modules/@chatbot/shared-lib
    command: npm run start:dev
    depends_on:
      - db
      - rabbitmq

  chatbot-chats:
    build:
      context: ./chatbot-chats
    ports:
      - "3003:3000"
    volumes:
      - ./chatbot-chats:/app
      - ./shared-lib:/app/node_modules/@chatbot/shared-lib
    command: npm run start:dev
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    logging:
      driver: "none"    

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging:
      driver: "none"

volumes:
  db_data:
    driver: local
  rabbitmq_data:
    driver: local
