//QUEUES
export const LOG_QUEUE = 'LOG_QUEUE';
export const USER_QUEUE = 'USER_QUEUE';
export const CHAT_QUEUE = 'CHAT_QUEUE';

//CHAT EVENTS
export const CHAT_CREATE_EVENT = 'CHAT_CREATE_EVENT';

//USER EVENTS
export const USER_ACCESS_EVENT = 'USER_ACCESS_EVENT';
export const USER_NEW_EVENT = 'USER_NEW_EVENT';

//MESSAGE EVENTS

